# Generated by Django 4.0.4 on 2022-05-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/clients')),
                ('Name', models.CharField(max_length=30)),
                ('PositionAndCompanyName', models.CharField(max_length=30)),
                ('Discription', models.CharField(max_length=200)),
                ('Fade', models.CharField(max_length=30)),
                ('Delay', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catagory', models.CharField(max_length=30)),
                ('Rating', models.IntegerField()),
                ('FullName', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/portfolio')),
                ('ProjectName', models.CharField(max_length=30)),
                ('ToolUsed', models.CharField(max_length=200)),
                ('Link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/services')),
                ('ServiceName', models.CharField(max_length=30)),
                ('Discription', models.CharField(max_length=200)),
                ('RedirectLink', models.CharField(max_length=200)),
                ('Fade', models.CharField(max_length=30)),
                ('Delay', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='images/team')),
                ('FullName', models.CharField(max_length=30)),
                ('Position', models.CharField(max_length=30)),
                ('Twitter', models.CharField(max_length=200)),
                ('Facebook', models.CharField(max_length=200)),
                ('Instagram', models.CharField(max_length=200)),
                ('LinkedIn', models.CharField(max_length=200)),
            ],
        ),
    ]
