# Generated by Django 4.0.4 on 2022-05-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Customers',
        ),
        migrations.AlterField(
            model_name='services',
            name='Discription',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='services',
            name='RedirectLink',
            field=models.CharField(max_length=500),
        ),
    ]
