# Generated by Django 4.0.4 on 2022-07-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_article_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(max_length=500),
        ),
    ]
