# Generated by Django 4.0.4 on 2022-07-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_alter_article_head_alter_article_headline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Popular',
        ),
        migrations.DeleteModel(
            name='Recommend',
        ),
    ]
