# Generated by Django 4.0.4 on 2022-07-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subscription',
        ),
    ]
